<?php

namespace Database\Seeders;

use App\Models\FormSubmission;
use Illuminate\Database\Seeder;

class FormSubmissionSeeder extends Seeder
{
    public function run(): void
    {
        $submissions = [
            [
                'first_name' => 'Sarah',
                'email' => 'sarah.namutebi@gmail.com',
                'status' => 'accepted',
                'data' => [
                    'first_name' => 'Sarah',
                    'middle_name' => 'Nakato',
                    'last_name' => 'Namutebi',
                    'email' => 'sarah.namutebi@gmail.com',
                    'phone' => '+256701234567',
                    'district' => 'Kampala',
                    'county' => 'Kampala Central',
                    'sub_county' => 'Nakawa',
                    'village' => 'Bukoto',
                    'date_of_birth' => '12/05/1998',
                    'gender' => 'Female',
                    'nin' => 'CM98120541KJKL',
                    'education_level' => "Bachelor's Degree",
                    'education_other' => '',
                    'tiktok' => '@sarah_nam',
                    'next_of_kin_name' => 'John Namutebi',
                    'next_of_kin_relationship' => 'Father',
                    'next_of_kin_phone' => '+256712345678',
                    'next_of_kin_nin' => 'CM70123451KJKL',
                    'hear_about' => 'Instagram',
                    'hear_about_other' => '',
                    'recommender' => 'None',
                    'personal_statement' => 'I am a recent graduate in Business Administration with a passion for entrepreneurship. Growing up in Kampala, I have always been fascinated by how small businesses can transform communities. I run a small side business making reusable sanitary pads, and I want to scale it to reach more girls in rural areas. This program will give me the skills and network to turn my passion into a sustainable social enterprise. I believe that with the right mentorship and training, I can create jobs and make a difference in my community.',
                    'business_description' => 'I run a small social enterprise called "EcoPads Uganda" that produces reusable sanitary pads for school girls in rural areas. Currently operating on a small scale with 3 part-time workers.',
                    'previous_programs' => 'Yes',
                    'skills_talents' => 'Sewing and tailoring, basic accounting, social media management, public speaking.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '2 years',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Daniel',
                'email' => 'daniel.okello@yahoo.com',
                'status' => 'pending',
                'data' => [
                    'first_name' => 'Daniel',
                    'middle_name' => 'Ochen',
                    'last_name' => 'Okello',
                    'email' => 'daniel.okello@yahoo.com',
                    'phone' => '+256772345678',
                    'district' => 'Gulu',
                    'county' => 'Gulu Municipality',
                    'sub_county' => 'Laroo',
                    'village' => 'Pece',
                    'date_of_birth' => '03/11/2000',
                    'gender' => 'Male',
                    'nin' => 'CM00110351KJKL',
                    'education_level' => 'Diploma',
                    'education_other' => '',
                    'tiktok' => '',
                    'next_of_kin_name' => 'Grace Okello',
                    'next_of_kin_relationship' => 'Mother',
                    'next_of_kin_phone' => '+256782345679',
                    'next_of_kin_nin' => '',
                    'hear_about' => 'Friend',
                    'hear_about_other' => '',
                    'recommender' => 'Peter Odongo',
                    'personal_statement' => 'I completed a diploma in Agriculture and have been working on my family farm. I want to learn modern farming techniques and business management to turn our small farm into a commercial enterprise. The program aligns with my goal of becoming an agri-preneur and creating employment for youth in Gulu. I have seen many young people struggle with unemployment, and I believe that agriculture is the key to economic transformation in northern Uganda.',
                    'business_description' => 'Family farm growing maize, beans, and groundnuts on 5 acres. We sell at local markets.',
                    'previous_programs' => 'No',
                    'skills_talents' => 'Farming, basic carpentry, football coaching.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '9 months',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Grace',
                'email' => 'grace.akello@gmail.com',
                'status' => 'reviewed',
                'data' => [
                    'first_name' => 'Grace',
                    'middle_name' => 'Achieng',
                    'last_name' => 'Akello',
                    'email' => 'grace.akello@gmail.com',
                    'phone' => '+256756789012',
                    'district' => 'Lira',
                    'county' => 'Lira District',
                    'sub_county' => 'Aromo',
                    'village' => 'Abako',
                    'date_of_birth' => '25/08/2002',
                    'gender' => 'Female',
                    'nin' => 'CM02082551KJKL',
                    'education_level' => 'UACE (S6)',
                    'education_other' => '',
                    'tiktok' => '',
                    'next_of_kin_name' => 'Michael Akello',
                    'next_of_kin_relationship' => 'Uncle',
                    'next_of_kin_phone' => '+256790123456',
                    'next_of_kin_nin' => '',
                    'hear_about' => 'Jangu website',
                    'hear_about_other' => '',
                    'recommender' => 'None',
                    'personal_statement' => 'I completed my A-levels last year and have been volunteering with a local women\'s group that does savings and loan activities. I want to study entrepreneurship because I see many women in my village who have skills but lack business knowledge to turn them into income. My dream is to start a training center that teaches women financial literacy and business skills. This program is the first step toward achieving that dream.',
                    'business_description' => 'Not currently running a business, but I help my aunt sell vegetables at the market on weekends.',
                    'previous_programs' => 'No',
                    'skills_talents' => 'Weaving, crafting, organizing community events, basic computer skills.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '9 months',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Isaac',
                'email' => 'isaac.kintu@outlook.com',
                'status' => 'pending',
                'data' => [
                    'first_name' => 'Isaac',
                    'middle_name' => 'Ssewankambo',
                    'last_name' => 'Kintu',
                    'email' => 'isaac.kintu@outlook.com',
                    'phone' => '+256789012345',
                    'district' => 'Wakiso',
                    'county' => 'Kyadondo',
                    'sub_county' => 'Gayaza',
                    'village' => 'Kiteezi',
                    'date_of_birth' => '15/01/1999',
                    'gender' => 'Male',
                    'nin' => 'CM99011551KJKL',
                    'education_level' => "Bachelor's Degree",
                    'education_other' => '',
                    'tiktok' => '@isaac_kintu',
                    'next_of_kin_name' => 'Rebecca Kintu',
                    'next_of_kin_relationship' => 'Mother',
                    'next_of_kin_phone' => '+256701234568',
                    'next_of_kin_nin' => 'CM75020141KJKL',
                    'hear_about' => 'Tiktok',
                    'hear_about_other' => '',
                    'recommender' => 'Sarah Nalwoga',
                    'personal_statement' => 'I am a computer science graduate who has been building mobile money agent solutions for small businesses. I want to join this program to learn how to structure my tech ideas into a viable business. I have built a prototype for a digital savings platform targeting SACCOs, and I need mentorship to launch it successfully. The program\'s focus on entrepreneurship will help me understand market dynamics, customer acquisition, and sustainable business modeling.',
                    'business_description' => 'I run a mobile money agent business and also do freelance web development for local SMEs.',
                    'previous_programs' => 'Yes',
                    'skills_talents' => 'Web development, mobile money operations, graphic design, basic electronics repair.',
                    'applied_before' => 'Yes',
                    'applied_times' => 'Ounce',
                    'time_commitment' => '2 years',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Aisha',
                'email' => 'aisha.nabbanja@gmail.com',
                'status' => 'rejected',
                'data' => [
                    'first_name' => 'Aisha',
                    'middle_name' => 'Nakato',
                    'last_name' => 'Nabbanja',
                    'email' => 'aisha.nabbanja@gmail.com',
                    'phone' => '+256701111222',
                    'district' => 'Jinja',
                    'county' => 'Jinja Municipality',
                    'sub_county' => 'Mafubira',
                    'village' => 'Wairaka',
                    'date_of_birth' => '08/03/2001',
                    'gender' => 'Female',
                    'nin' => 'CM01030851KJKL',
                    'education_level' => 'UCE (S4)',
                    'education_other' => '',
                    'tiktok' => '',
                    'next_of_kin_name' => 'Hassan Nabbanja',
                    'next_of_kin_relationship' => 'Father',
                    'next_of_kin_phone' => '+256701111333',
                    'next_of_kin_nin' => '',
                    'hear_about' => 'Facebook',
                    'hear_about_other' => '',
                    'recommender' => 'None',
                    'personal_statement' => 'I completed S4 and have been working in a salon for two years. I want to start my own salon business and employ other young women. I have learned hairdressing, manicure, and pedicure, and I believe I have what it takes to run a successful beauty business.',
                    'business_description' => 'Not yet, but I plan to open a salon.',
                    'previous_programs' => 'No',
                    'skills_talents' => 'Hairdressing, makeup artistry, customer service.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '3 months',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Robert',
                'email' => 'robert.ssekyene@gmail.com',
                'status' => 'pending',
                'data' => [
                    'first_name' => 'Robert',
                    'middle_name' => 'Kato',
                    'last_name' => 'Ssekyene',
                    'email' => 'robert.ssekyene@gmail.com',
                    'phone' => '+256778889999',
                    'district' => 'Mbale',
                    'county' => 'Mbale Municipality',
                    'sub_county' => 'Namatala',
                    'village' => 'Namatala',
                    'date_of_birth' => '20/10/1997',
                    'gender' => 'Male',
                    'nin' => 'CM97102051KJKL',
                    'education_level' => 'PLE (P7)',
                    'education_other' => '',
                    'tiktok' => '',
                    'next_of_kin_name' => 'Mary Ssekyene',
                    'next_of_kin_relationship' => 'Sister',
                    'next_of_kin_phone' => '+256778888000',
                    'next_of_kin_nin' => '',
                    'hear_about' => 'Friend',
                    'hear_about_other' => '',
                    'recommender' => 'Joseph Wafula',
                    'personal_statement' => 'I left school after P7 due to lack of fees, but I have been working as a boda boda rider and saving money. I want to learn business skills so I can invest my savings into a proper transport business. I know how to repair motorcycles and want to open a garage that also hires out boda bodas. This program will help me get the knowledge I missed in school.',
                    'business_description' => 'I own one motorcycle that I use for boda boda transport. I also do basic motorcycle repairs.',
                    'previous_programs' => 'No',
                    'skills_talents' => 'Motorcycle riding and repair, basic welding.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '9 months',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
            [
                'first_name' => 'Esther',
                'email' => 'esther.nabwire@yahoo.com',
                'status' => 'accepted',
                'data' => [
                    'first_name' => 'Esther',
                    'middle_name' => 'Nasimiyu',
                    'last_name' => 'Nabwire',
                    'email' => 'esther.nabwire@yahoo.com',
                    'phone' => '+256700123987',
                    'district' => 'Tororo',
                    'county' => 'Tororo Municipality',
                    'sub_county' => 'Township',
                    'village' => 'Omunyal',
                    'date_of_birth' => '05/06/2000',
                    'gender' => 'Female',
                    'nin' => 'CM00060551KJKL',
                    'education_level' => 'Diploma',
                    'education_other' => '',
                    'tiktok' => '@esther_nabs',
                    'next_of_kin_name' => 'David Nabwire',
                    'next_of_kin_relationship' => 'Father',
                    'next_of_kin_phone' => '+256700123988',
                    'next_of_kin_nin' => 'CM75010141KJKL',
                    'hear_about' => 'Linked In',
                    'hear_about_other' => '',
                    'recommender' => 'None',
                    'personal_statement' => 'I have a diploma in Nutrition and run a small catering business. I want to scale up and open a restaurant that serves healthy, affordable meals. I am particularly passionate about nutrition education and want to combine my catering business with community health talks. The entrepreneurship program will help me develop a solid business plan and learn financial management.',
                    'business_description' => 'Catering service for small events. I employ two women part-time. Revenue is about 500,000 UGX per month.',
                    'previous_programs' => 'Yes',
                    'skills_talents' => 'Cooking and baking, nutrition planning, event organizing.',
                    'applied_before' => 'No',
                    'applied_times' => 'Never',
                    'time_commitment' => '2 years',
                    'time_commitment_other' => '',
                    'consent_1' => 'checked',
                    'consent_2' => 'checked',
                ],
            ],
        ];

        foreach ($submissions as $submission) {
            FormSubmission::create($submission);
        }
    }
}
